services:
  - type: web
    name: sketchmind-api
    runtime: docker
    branch: frontend-final
    dockerfilePath: ./backend/Dockerfile
    dockerContext: .
    healthCheckPath: /api/health
    envVars:
      - key: ALLOWED_ORIGINS
        sync: false
