import tensorflow as tf
import numpy as np
from PIL import Image
import os


class Predictor:

    def __init__(self):

        self.model = None
        self.labels = []

        # Get the directory where this file is located
        self.script_dir = os.path.dirname(os.path.abspath(__file__))

        self.load_labels()
        self.load_model()

    # ========================================================
    # LOAD LABELS
    # ========================================================

    def load_labels(self):

        # First try the labels generated by preprocessing
        processed_labels = os.path.join(
            self.script_dir,
            "processed",
            "labels.txt"
        )

        # Fallback to model-training/labels.txt
        normal_labels = os.path.join(
            self.script_dir,
            "labels.txt"
        )

        if os.path.exists(processed_labels):

            labels_path = processed_labels

        elif os.path.exists(normal_labels):

            labels_path = normal_labels

        else:

            raise FileNotFoundError(
                f"labels.txt not found in {self.script_dir} or {os.path.join(self.script_dir, 'processed')}"
            )

        with open(
            labels_path,
            "r",
            encoding="utf-8"
        ) as f:

            self.labels = [
                line.strip().lower()
                for line in f
                if line.strip()
            ]

        print(
            "Loaded labels:",
            self.labels
        )

    # ========================================================
    # LOAD MODEL
    # ========================================================

    def load_model(self):

        possible_models = [

            # Model created by our training script
            os.path.join(
                self.script_dir,
                "models",
                "quickdraw_model.keras"
            ),

            # Best model created during training
            os.path.join(
                self.script_dir,
                "models",
                "quickdraw_best.keras"
            ),

            # Existing repository model
            os.path.join(
                self.script_dir,
                "sketchmind_model.keras"
            )
        ]

        model_path = None

        for path in possible_models:

            if os.path.exists(path):

                model_path = path
                break

        if model_path is None:

            raise FileNotFoundError(
                "No trained model found.\n"
                "Expected one of:\n"
                + "\n".join(possible_models)
            )

        print(
            f"Loading model: {model_path}"
        )

        self.model = tf.keras.models.load_model(
            model_path
        )

        print(
            "Model loaded successfully."
        )

        print(
            "Model output classes:",
            self.model.output_shape[-1]
        )

        print(
            "Number of labels:",
            len(self.labels)
        )

        if (
            self.model.output_shape[-1]
            != len(self.labels)
        ):

            raise ValueError(
                "\nModel/label mismatch!\n"
                f"Model outputs: "
                f"{self.model.output_shape[-1]}\n"
                f"Labels: "
                f"{len(self.labels)}"
            )

    # ========================================================
    # PREPROCESS DRAWING
    # ========================================================

    def preprocess(self, image):

        # ----------------------------------------------------
        # Convert to grayscale
        # ----------------------------------------------------

        image = image.convert("L")

        img = np.array(image)

        # ----------------------------------------------------
        # Make sure drawing is white on black
        # ----------------------------------------------------

        # Canvas is already expected to be:
        #
        # background = 0
        # drawing    = 255
        #
        # If the image is inverted, correct it.

        if img.mean() > 127:

            img = 255 - img

        # ----------------------------------------------------
        # Remove very faint pixels
        # ----------------------------------------------------

        threshold = 20

        binary = img > threshold

        # ----------------------------------------------------
        # Find drawing bounding box
        # ----------------------------------------------------

        coords = np.argwhere(binary)

        if coords.size == 0:

            # Empty canvas
            return np.zeros(
                (1, 28, 28, 1),
                dtype=np.float32
            )

        y_min, x_min = coords.min(axis=0)
        y_max, x_max = coords.max(axis=0)

        # ----------------------------------------------------
        # Crop drawing
        # ----------------------------------------------------

        cropped = img[
            y_min:y_max + 1,
            x_min:x_max + 1
        ]

        # ----------------------------------------------------
        # Add padding
        # ----------------------------------------------------

        h, w = cropped.shape

        size = max(h, w)

        padding = int(size * 0.25)

        canvas_size = size + (
            padding * 2
        )

        centered = np.zeros(
            (canvas_size, canvas_size),
            dtype=np.uint8
        )

        y_offset = (
            canvas_size - h
        ) // 2

        x_offset = (
            canvas_size - w
        ) // 2

        centered[
            y_offset:y_offset + h,
            x_offset:x_offset + w
        ] = cropped

        # ----------------------------------------------------
        # Resize to QuickDraw dimensions
        # ----------------------------------------------------

        processed = Image.fromarray(
            centered
        )

        processed = processed.resize(
            (28, 28),
            Image.Resampling.LANCZOS
        )

        img = np.array(
            processed
        ).astype(
            np.float32
        )

        # ----------------------------------------------------
        # Normalize exactly like training
        # ----------------------------------------------------

        img = img / 255.0

        # ----------------------------------------------------
        # Add channel dimension
        # ----------------------------------------------------

        img = np.expand_dims(
            img,
            axis=-1
        )

        # ----------------------------------------------------
        # Add batch dimension
        # ----------------------------------------------------

        img = np.expand_dims(
            img,
            axis=0
        )

        return img

    # ========================================================
    # PREDICT
    # ========================================================

    def predict(self, image):

        img = self.preprocess(
            image
        )

        prediction = self.model.predict(
            img,
            verbose=0
        )[0]

        # Top prediction
        index = int(
            np.argmax(prediction)
        )

        confidence = float(
            prediction[index]
        )

        label = self.labels[index]

        return label, confidence

    # ========================================================
    # TOP 3 PREDICTIONS
    # ========================================================

    def predict_top3(self, image):

        img = self.preprocess(
            image
        )

        prediction = self.model.predict(
            img,
            verbose=0
        )[0]

        indices = np.argsort(
            prediction
        )[::-1][:3]

        results = []

        for index in indices:

            results.append({
                "label": self.labels[index],
                "confidence": float(
                    prediction[index]
                )
            })

        return results